/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mpXSJH0xrid
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <section className="grid grid-cols-1 md:grid-cols-2 gap-6 p-4 md:p-6">
      <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View</span>
        </Link>
        <img
          alt="Food Item 1"
          className="object-cover w-full h-64"
          height="300"
          src="/placeholder.svg"
          style={{
            aspectRatio: "400/300",
            objectFit: "cover",
          }}
          width="400"
        />
        <div className="bg-white p-4 dark:bg-gray-950">
          <h3 className="font-bold text-xl">Grilled Salmon</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Fresh salmon fillet grilled to perfection, served with a side of roasted vegetables.
          </p>
          <div className="flex justify-between items-center mt-4">
            <Button size="sm" variant="outline">
              <ThumbsUpIcon className="w-4 h-4 mr-2" />
              Like
            </Button>
            <Button size="sm" variant="outline">
              <ThumbsDownIcon className="w-4 h-4 mr-2" />
              Dislike
            </Button>
          </div>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View</span>
        </Link>
        <img
          alt="Food Item 2"
          className="object-cover w-full h-64"
          height="300"
          src="/placeholder.svg"
          style={{
            aspectRatio: "400/300",
            objectFit: "cover",
          }}
          width="400"
        />
        <div className="bg-white p-4 dark:bg-gray-950">
          <h3 className="font-bold text-xl">Beef Burrito</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Tender beef, rice, beans, and fresh veggies wrapped in a warm tortilla.
          </p>
          <div className="flex justify-between items-center mt-4">
            <Button size="sm" variant="outline">
              <ThumbsUpIcon className="w-4 h-4 mr-2" />
              Like
            </Button>
            <Button size="sm" variant="outline">
              <ThumbsDownIcon className="w-4 h-4 mr-2" />
              Dislike
            </Button>
          </div>
        </div>
      </div>
    </section>
  )
}

function ThumbsDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 14V2" />
      <path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22h0a3.13 3.13 0 0 1-3-3.88Z" />
    </svg>
  )
}


function ThumbsUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}
