import RestaurantsLikedProvider from '@/lib/restaurants-liked'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})
export const metadata: Metadata = {
  title: 'Tinder restaurant',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          'bg-gray-100 dark:bg-gray-900',
          fontSans.variable
        )}
      >
        <RestaurantsLikedProvider>{children}</RestaurantsLikedProvider>
      </body>
    </html>
  )
}
